### ISSUE TITLE
Package doesn’t exist on npm

### ISSUE THREAD

**Issue by gosseti** [kuy/redux-tower#32]
I just tried to install the package and got:

```
Registry returned 404 for GET on https://registry.npmjs.org/redux-tower
```

Also see [here](https://www.npmjs.com/search?q=redux-tower)

**Comment by kuy** [comment]
@gosseti Oops, I didn't write it on README. But I'll release in hours 😃

**Comment by kuy** [comment]
Released ! 🎉 
https://www.npmjs.com/package/redux-tower
